#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_TABLE_NAME_LENGTH 32
#define MAX_COLUMN_NAME_LENGTH 32
#define MAX_STRING_LENGTH 32
#define MAX_COLUMNS 8
#define HASHMAP_SIZE 10

#endif // CONSTANTS_H